package org.wbhack.coach

/** UI copy. Spanish screens follow the Spanish coaching language; Tamil keeps English navigation (draft content). */
data class UiText(
    val tabs: List<String>,
    val welcomeBack: String,
    val tagline: String,
    val checking: String,
    val aiOnTitle: String,
    val aiOnBody: (String) -> String,
    val aiOffTitle: String,
    val aiOffBody: String,
    val aiNoLanguageBody: String,
    val progress: (Int, Int) -> String,
    val nextConversation: String,
    val practiceAgain: String,
    val startHere: String,
    val openPractice: String,
    val footer: String,
    val welcomeTitle: String,
    val welcomeBody: String,
    val safeTitle: String,
    val safeBody: String,
    val previewTitle: String,
    val previewBody: String,
    val start: String,
    val allScenarios: String,
    val freshSituation: String,
    val guestAsks: String,
    val aiGuestAsks: String,
    val facts: String,
    val factsList: String,
    val factsNote: String,
    val replyLabel: String,
    val replyCounter: (Int) -> String,
    val useSaved: (String) -> String,
    val compare: String,
    val getAiCoaching: String,
    val aiWorking: String,
    val aiErrorTitle: String,
    val retry: String,
    val useGuide: String,
    val oneThing: String,
    val selfCheck: String,
    val example: String,
    val fixedNote: String,
    val strength: String,
    val improvement: String,
    val evidence: String,
    val uncertainTitle: String,
    val uncertainBody: String,
    val scoresTitle: String,
    val scoreLabels: Map<String, String>,
    val aiNote: String,
    val accept: String,
    val reject: String,
    val accepted: String,
    val rejected: String,
    val nextGuest: String,
    val improve: String,
    val remember: String,
    val tryNew: String,
    val finish: String,
    val saveTitle: String,
    val saveBody: String,
    val approvedWording: String,
    val approveSave: String,
    val cancel: String,
    val phrasesTitle: String,
    val phrasesBody: String,
    val emptyTitle: String,
    val emptyBody: String,
    val forget: String,
    val settingsTitle: String,
    val deviceTitle: String,
    val deviceBody: String,
    val modelTitle: String,
    val modelOn: (String) -> String,
    val modelOff: String,
    val backendLabel: String,
    val saveAndCheck: String,
    val languageNote: String,
    val clearData: String,
    val resetTitle: String,
    val resetBody: String,
    val confirmClear: String,
    val keepData: String,
    val languageLabel: String,
    val titles: Map<String, String>,
)

private val EN = UiText(
    tabs = listOf("Practice", "My phrases", "Settings"),
    welcomeBack = "Welcome back.",
    tagline = "A little practice.\nA more confident welcome.",
    checking = "Looking for the AI coach…",
    aiOnTitle = "AI coach connected",
    aiOnBody = { "Guest questions and feedback come from $it running on your local computer. Nothing is sent to the cloud or to a guest." },
    aiOffTitle = "Offline practice guide",
    aiOffBody = "The AI coach is not reachable, so practice uses fixed example cards. Saved phrases stay on this device.",
    aiNoLanguageBody = "The AI coach supports Español and தமிழ். English uses the fixed practice guide.",
    progress = { sessions, explored -> "$sessions practice sessions · $explored of 3 scenarios explored" },
    nextConversation = "Your next conversation",
    practiceAgain = "PRACTICE AGAIN",
    startHere = "START HERE",
    openPractice = "Open practice →",
    footer = "Fictional farm scenarios · English guest dialogue · Experimental coaching languages",
    welcomeTitle = "Make every\nwelcome count.",
    welcomeBody = "Try a guest conversation, get feedback on your reply, then try again.",
    safeTitle = "A space to practise",
    safeBody = "Nothing is sent to a guest. Only phrases you choose to remember are saved. This is a shared-device prototype: anyone with access to this app can see saved phrases.",
    previewTitle = "Early preview",
    previewBody = "AI feedback comes from a small local model and can be wrong. You decide whether to accept it. Tamil text is a draft awaiting a local-language reviewer.",
    start = "Start practising",
    allScenarios = "← All scenarios",
    freshSituation = "A fresh situation",
    guestAsks = "Imagine your guest asks…",
    aiGuestAsks = "Your AI guest asks…",
    facts = "Facts you can rely on",
    factsList = "Standard tour: 60 minutes\nCoffee tasting: 20 minutes\nMeeting point: farm entrance beside the blue gate\nPrices and availability: not confirmed",
    factsNote = "These are fictional demo facts.",
    replyLabel = "Your reply to the guest",
    replyCounter = { "$it/2000 · This draft is not saved on this phone" },
    useSaved = { "Use saved phrase: $it" },
    compare = "Compare with practice guide",
    getAiCoaching = "Get AI feedback",
    aiWorking = "The AI coach is thinking… this can take a minute.",
    aiErrorTitle = "The AI coach could not answer",
    retry = "Try again",
    useGuide = "Use the offline practice guide",
    oneThing = "One thing to practise",
    selfCheck = "Self-check",
    example = "An example reply",
    fixedNote = "Fixed reference guidance—not an assessment of your response.",
    strength = "What worked",
    improvement = "One thing to improve",
    evidence = "From your reply",
    uncertainTitle = "The AI is unsure",
    uncertainBody = "Treat this feedback with extra care. Check it against the facts before using it.",
    scoresTitle = "Checklist (0–2)",
    scoreLabels = mapOf("answers_request" to "Answers the request", "factual_accuracy" to "Uses only confirmed facts",
        "clarifies_unknowns" to "Clarifies what is not confirmed", "next_step" to "Offers a next step"),
    aiNote = "Generated by a local AI model. It can be wrong; only feedback you accept counts toward progress.",
    accept = "Accept feedback",
    reject = "Reject",
    accepted = "Accepted — saved to your progress.",
    rejected = "Rejected — not counted.",
    nextGuest = "Next guest question",
    improve = "Improve my reply",
    remember = "Remember my phrase…",
    tryNew = "Try a new version of this situation",
    finish = "Finish practice",
    saveTitle = "Remember this phrase?",
    saveBody = "Edit before approving. It will be saved for this scenario and, when connected, shared with your local AI coach. Do not include private guest details.",
    approvedWording = "Approved wording",
    approveSave = "Approve & save",
    cancel = "Cancel",
    phrasesTitle = "Words that work\nfor you.",
    phrasesBody = "Only wording you approve appears here. Reuse it in practice, or remove it at any time.",
    emptyTitle = "Your phrasebook is ready",
    emptyBody = "After a practice round, choose ‘Remember my phrase’ to add your own wording.",
    forget = "Forget phrase",
    settingsTitle = "Make it yours.",
    deviceTitle = "On this phone",
    deviceBody = "Approved phrases, language preference and practice counts are stored locally. Replies are only sent to the AI coach address below. Android backup is disabled.",
    modelTitle = "AI coach",
    modelOn = { "Connected: $it on your local computer. No cloud fallback." },
    modelOff = "Not connected. Start the backend (python3 -m hospitality.server) with Ollama, then run `adb reverse tcp:8765 tcp:8765`.",
    backendLabel = "AI coach address",
    saveAndCheck = "Save & check connection",
    languageNote = "Coaching languages are experimental and not validated by native speakers. Guest prompts are in English.",
    clearData = "Clear phrases and progress…",
    resetTitle = "Clear local learning data?",
    resetBody = "This removes all approved phrases and practice counts on this phone. It cannot be undone.",
    confirmClear = "Clear data",
    keepData = "Keep data",
    languageLabel = "Coaching language",
    titles = mapOf("time_request" to "A guest in a hurry", "directions" to "A warm welcome", "duration_availability" to "Planning a visit"),
)

private val ES = EN.copy(
    tabs = listOf("Practicar", "Mis frases", "Ajustes"),
    welcomeBack = "¡Bienvenido de nuevo!",
    tagline = "Un poco de práctica.\nUna bienvenida con más confianza.",
    checking = "Buscando el coach de IA…",
    aiOnTitle = "Coach de IA conectado",
    aiOnBody = { "Las preguntas del huésped y los comentarios vienen de $it en tu computadora local. Nada se envía a la nube ni a un huésped." },
    aiOffTitle = "Guía de práctica sin conexión",
    aiOffBody = "No se puede contactar al coach de IA, así que la práctica usa tarjetas de ejemplo fijas. Tus frases guardadas se quedan en este teléfono.",
    progress = { sessions, explored -> "$sessions prácticas · $explored de 3 situaciones exploradas" },
    nextConversation = "Tu próxima conversación",
    practiceAgain = "PRACTICAR DE NUEVO",
    startHere = "EMPIEZA AQUÍ",
    openPractice = "Abrir práctica →",
    footer = "Situaciones ficticias en una finca · Huéspedes en inglés · Coaching en español (experimental)",
    welcomeTitle = "Haz que cada\nbienvenida cuente.",
    welcomeBody = "Practica una conversación con un huésped, recibe comentarios sobre tu respuesta y vuelve a intentarlo.",
    safeTitle = "Un espacio para practicar",
    safeBody = "Nada se envía a un huésped. Solo se guardan las frases que tú elijas. Es un prototipo para un dispositivo compartido: cualquiera con acceso a esta app puede ver las frases guardadas.",
    previewTitle = "Versión preliminar",
    previewBody = "Los comentarios vienen de un modelo de IA pequeño y local, y pueden equivocarse. Tú decides si los aceptas.",
    start = "Empezar a practicar",
    allScenarios = "← Todas las situaciones",
    freshSituation = "Una situación nueva",
    guestAsks = "Imagina que tu huésped pregunta…",
    aiGuestAsks = "Tu huésped de IA pregunta…",
    facts = "Datos confirmados",
    factsList = "Recorrido estándar: 60 minutos\nDegustación de café: 20 minutos\nPunto de encuentro: entrada de la finca, junto a la puerta azul\nPrecios y disponibilidad: sin confirmar",
    factsNote = "Son datos ficticios de demostración.",
    replyLabel = "Tu respuesta al huésped (en inglés)",
    replyCounter = { "$it/2000 · Este borrador no se guarda en el teléfono" },
    useSaved = { "Usar frase guardada: $it" },
    compare = "Comparar con la guía de práctica",
    getAiCoaching = "Recibir comentarios de la IA",
    aiWorking = "El coach de IA está pensando… puede tardar un minuto.",
    aiErrorTitle = "El coach de IA no pudo responder",
    retry = "Intentar de nuevo",
    useGuide = "Usar la guía sin conexión",
    oneThing = "Algo para practicar",
    selfCheck = "Autoevaluación",
    example = "Un ejemplo de respuesta",
    fixedNote = "Guía de referencia fija; no es una evaluación de tu respuesta.",
    strength = "Lo que funcionó",
    improvement = "Algo para mejorar",
    evidence = "De tu respuesta",
    uncertainTitle = "La IA no está segura",
    uncertainBody = "Revisa este comentario con cuidado y compáralo con los datos confirmados antes de usarlo.",
    scoresTitle = "Lista de control (0–2)",
    scoreLabels = mapOf("answers_request" to "Responde a la pregunta", "factual_accuracy" to "Usa solo datos confirmados",
        "clarifies_unknowns" to "Aclara lo que no está confirmado", "next_step" to "Propone un siguiente paso"),
    aiNote = "Generado por un modelo de IA local. Puede equivocarse; solo los comentarios que aceptes cuentan para tu progreso.",
    accept = "Aceptar comentario",
    reject = "Rechazar",
    accepted = "Aceptado: guardado en tu progreso.",
    rejected = "Rechazado: no se cuenta.",
    nextGuest = "Siguiente pregunta del huésped",
    improve = "Mejorar mi respuesta",
    remember = "Recordar mi frase…",
    tryNew = "Probar otra versión de esta situación",
    finish = "Terminar práctica",
    saveTitle = "¿Recordar esta frase?",
    saveBody = "Edítala antes de aprobarla. Se guardará para esta situación y, con conexión, se compartirá con tu coach de IA local. No incluyas datos privados de huéspedes.",
    approvedWording = "Frase aprobada",
    approveSave = "Aprobar y guardar",
    cancel = "Cancelar",
    phrasesTitle = "Palabras que\nte funcionan.",
    phrasesBody = "Aquí solo aparecen las frases que apruebes. Reutilízalas al practicar o elimínalas cuando quieras.",
    emptyTitle = "Tu libreta de frases está lista",
    emptyBody = "Después de practicar, elige ‘Recordar mi frase’ para añadir tus propias palabras.",
    forget = "Olvidar frase",
    settingsTitle = "Hazla tuya.",
    deviceTitle = "En este teléfono",
    deviceBody = "Las frases aprobadas, el idioma y el número de prácticas se guardan en el teléfono. Las respuestas solo se envían a la dirección del coach de IA indicada abajo. La copia de seguridad de Android está desactivada.",
    modelTitle = "Coach de IA",
    modelOn = { "Conectado: $it en tu computadora local. Sin respaldo en la nube." },
    modelOff = "Sin conexión. Inicia el backend (python3 -m hospitality.server) con Ollama y luego ejecuta `adb reverse tcp:8765 tcp:8765`.",
    backendLabel = "Dirección del coach de IA",
    saveAndCheck = "Guardar y comprobar conexión",
    languageNote = "Los idiomas de coaching son experimentales y no han sido validados por hablantes nativos. Las preguntas de los huéspedes están en inglés.",
    clearData = "Borrar frases y progreso…",
    resetTitle = "¿Borrar los datos de aprendizaje?",
    resetBody = "Esto elimina todas las frases aprobadas y el número de prácticas en este teléfono. No se puede deshacer.",
    confirmClear = "Borrar datos",
    keepData = "Conservar datos",
    languageLabel = "Idioma del coaching",
    titles = mapOf("time_request" to "Un huésped con prisa", "directions" to "Una cálida bienvenida", "duration_availability" to "Planear una visita"),
)

/** Coaching languages the desktop backend accepts (`Coach.save_profile`). */
val AI_LANGUAGES = setOf("es", "ta")

fun uiText(language: String): UiText = if (language == "es") ES else EN
